/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UDj2L058Cig
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function SignIn2() {
  return (
    <>
      <div className="px-4 py-12">
        <div className="mx-auto max-w-3xl space-y-10">
          <div className="space-y-2">
            <div className="flex justify-between items-center">
              <div className="flex space-x-2">
                <div className="w-3 h-3 rounded-full bg-gray-300" />
                <div className="w-3 h-3 rounded-full bg-gray-500" />
                <div className="w-3 h-3 rounded-full bg-gray-300" />
              </div>
              <p className="text-sm text-gray-100">Stage 2 of 3</p>
            </div>
            <h1 className="text-4xl font-bold text-white">Sign In to CineMate</h1>
            <p className="text-gray-300 ">
              Enter the personal information and movie's preferences you have
            </p>
          </div>
          <div>
            <h1 className="text-2xl text-white font-semibold">Personal Preferences</h1>
            <div className="grid grid-cols-1 md:grid-cols-1 gap-4">
              <div className="space-y-2">
                <Label htmlFor="favorite-genres" className="text-white" >Favorite Genres</Label>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <Input id="genre-action" placeholder="First" />
                  <Input id="genre-comedy" placeholder="Second" />
                  <Input id="genre-drama" placeholder="Third" />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="latest-year"  className="text-white">Latest Year</Label>
                <Input id="latest-year" placeholder="Enter latest year" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="origin" className="text-white">Origin</Label>
                <Input id="origin" placeholder="Enter origin" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="favorite-company" className="text-white">Favorite Company</Label>
                <Input id="favorite-company" placeholder="Enter favorite company" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="max-runtime" className="text-white">Maximum Run Time</Label>
                <Input id="max-runtime" placeholder="Enter maximum run time" />
              </div>
            </div>
          </div>
          <Button className="w-full p-6 bg-slate-700  text-2xl">Submit</Button>
        </div>
      </div>
    </>
  )
}
