import Header from "@/components/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movies Recommender",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#1A1C29]">
       
      
        {children}
        <Header />
        
        </body>
    </html>
  );
}
