import Header from "@/components/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movies Recommender",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      
       
        <Header  />
        {children}
        
        
        
        
    </section>
  );
}
