import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Template from "./Templaite";

const inter = Inter({ subsets: ["latin"] });
//${inter.className}
export const metadata: Metadata = {
  title: "Movies Recommender",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-[#1A1C29]">
     
        {children}
        
        
        
        </body>

        {/*<div className="text-gray-400 bg-gray-950 flex flex-col items-center justify-between">
          <footer className="h-16 w-full related bottom-0  bg-gray-950 "><small className="absolute mt-6 ml-96 left-96 px-10 items-center justify-between">Powered by Shaked && David</small></footer>
  </div>*/}
    </html>
  );
}
