import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movies Recommender",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="${inter.className} bg-[#1A1C29]">
     
        {children}
        
        
        
        </body>

        <div className="text-gray-400 bg-gray-950 flex flex-col items-center justify-between">
          <footer className="h-24"><small>Powered by Shaked && David</small></footer>
        </div>
    </html>
  );
}
